version: '3'
services:
  generate:
    build:
      context: ./generate
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    environment:
      - CONFIG_PATH=./config/config.yaml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./generate/config/prometheus.yml:/etc/prometheus/prometheus.yml

volumes:
  grafana_data: