name: Test and pull request

on: 
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Install dependencies
        run: |
          cd generate
          go mod download

  merge:
    needs: test
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Merge PR
        run: |
          git config --global user.name 'my-bot'
          git config --global user.email 'my-bot@users.noreply.github.com'
          git checkout main
          git merge ${{ github.head_ref }}
          git push origin main
